name: Update icons

# Manual trigger
on: workflow_dispatch

env:
  FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
  FIGMA_FILE: ${{ secrets.FIGMA_FILE }}

jobs:
  update:
    name: Update icons
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/gallium'
      - name: Retrieve the cached "node_modules" directory (if present)
        uses: actions/cache@v2
        id: node-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies (if the cached directory was not found)
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
      - name: Update icons
        run: npm run start
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update icons
          comitter: ${{ secrets.COMITTER }}
          author: Dennis Mader <${{ secrets.COMITTER }}>
          branch: update-icons
          delete-branch: true
          branch-suffix: timestamp
          title: Update icons
          assignees: Weltraumakustik