name: Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'packages/component-library/**'

jobs:
  create-storybook-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Create the static pages directory locally in CI
        run: pnpm --prefix ./packages/component-library run build-storybook

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: packages/component-library/storybook-static
          clean-exclude: pr-preview/
