name: Deployment

on:
  push:
    branches:
      - main

jobs:
  create_storybook_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install main dependencies
        run: pnpm ci

      - name: Create the static pages directory locally in CI
        run: pnpm --prefix ./packages/component-library run build-storybook

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          force: false
          branch: gh-pages
          folder: storybook-static
          clean-exclude: pr-preview/
