name: Deploy PR previews

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'packages/component-library/**'

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install main dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Create the static pages directory locally in CI
        run: pnpm --filter @shopware-ag/meteor-component-library run build-storybook

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./packages/component-library/storybook-static/
