name: Tests

on:
  pull_request:

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: pnpm i

      - name: Check formatting
        run: pnpm run format:check

      - name: Perform typecheck
        run: pnpm run lint:types

      - name: Lint code
        run: pnpm run lint:eslint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: unit
        run: pnpm run test:unit

  circular-dependencies:
    name: Check for circular dependencies (Madge)
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: madge
        run: pnpm --filter @shopware-ag/meteor-admin-sdk run circular-dependencies

  playwright-run:
    name: Playwright Integration Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs: 
      - circular-dependencies
      - unit-tests
      - static-analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Install Playwright
        run: npx playwright install

      - name: Run Playwright tests
        run: pnpm --filter @shopware-ag/meteor-admin-sdk run test:e2e

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: meteor-admin-sdk--playwright-test-results
          path: packages/admin-sdk/playwright-report/
